import React, { useState, useEffect } from 'react';
import { MapPin, Calendar, CheckCircle, Clock, Target, BookOpen, Users, DollarSign, TrendingUp, Download } from 'lucide-react';

const CareerRoadmapGenerator = ({ selectedCareer, assessmentResults }) => {
  const [roadmapData, setRoadmapData] = useState(null);
  const [completedMilestones, setCompletedMilestones] = useState([]);
  const [selectedPhase, setSelectedPhase] = useState(null);
  const [showUniversities, setShowUniversities] = useState(false);

  // Mock roadmap data - in real app, this would be generated by AI
  const generateRoadmap = () => {
    const currentYear = new Date().getFullYear();
    const roadmap = {
      career: selectedCareer?.career || 'Software Engineer',
      totalDuration: '6-8 years',
      phases: [
        {
          id: 'current',
          title: 'Current Position',
          subtitle: 'SS3 Student',
          duration: 'Now',
          status: 'active',
          progress: 100,
          actions: [
            'Complete WAEC with excellent grades',
            'Prepare intensively for JAMB',
            'Build foundational programming skills',
            'Join coding communities online'
          ],
          skills: ['Basic Programming', 'Problem Solving', 'Mathematics'],
          milestones: [
            { id: 1, text: 'Score 280+ in JAMB', deadline: `${currentYear}-05-15`, completed: false },
            { id: 2, text: 'Complete Python basics course', deadline: `${currentYear}-04-01`, completed: false },
            { id: 3, text: 'Build first simple project', deadline: `${currentYear}-06-01`, completed: false }
          ],
          resources: [
            'FreeCodeCamp Python Course',
            'JAMB past questions (2015-2024)',
            'Codecademy free tier',
            'YouTube: Programming with Mosh'
          ]
        },
        {
          id: 'jamb',
          title: 'JAMB Preparation',
          subtitle: 'University Entrance',
          duration: '3-6 months',
          status: 'upcoming',
          progress: 0,
          actions: [
            'Intensive JAMB preparation',
            'University research and applications',
            'Scholarship applications',
            'Continue coding practice'
          ],
          skills: ['Test-taking strategies', 'Time management', 'Academic excellence'],
          milestones: [
            { id: 4, text: 'Complete JAMB registration', deadline: `${currentYear}-02-15`, completed: false },
            { id: 5, text: 'Take JAMB exam', deadline: `${currentYear}-05-15`, completed: false },
            { id: 6, text: 'Apply to 5 universities', deadline: `${currentYear}-06-30`, completed: false }
          ],
          resources: [
            'JAMB CBT practice software',
            'University admission requirements guide',
            'Scholarship databases',
            'JAMB syllabus and past questions'
          ]
        },
        {
          id: 'university',
          title: 'University Years',
          subtitle: 'Computer Science Degree',
          duration: '4-5 years',
          status: 'future',
          progress: 0,
          actions: [
            'Excel in core CS courses',
            'Join tech clubs and societies',
            'Build portfolio projects',
            'Seek internship opportunities'
          ],
          skills: ['Advanced Programming', 'Software Engineering', 'Data Structures', 'Algorithms'],
          milestones: [
            { id: 7, text: 'Maintain 4.5+ CGPA in Year 1', deadline: `${currentYear + 1}-07-01`, completed: false },
            { id: 8, text: 'Complete first internship', deadline: `${currentYear + 2}-12-01`, completed: false },
            { id: 9, text: 'Build 5 portfolio projects', deadline: `${currentYear + 3}-06-01`, completed: false },
            { id: 10, text: 'Graduate with First Class', deadline: `${currentYear + 4}-11-01`, completed: false }
          ],
          resources: [
            'University curriculum and courses',
            'GitHub for project hosting',
            'LinkedIn for networking',
            'Tech meetups and conferences'
          ]
        },
        {
          id: 'internships',
          title: 'Internships & Experience',
          subtitle: 'Practical Skills Development',
          duration: '1-2 years',
          status: 'future',
          progress: 0,
          actions: [
            'Apply to top tech companies',
            'Contribute to open source projects',
            'Build professional network',
            'Develop specialization area'
          ],
          skills: ['Professional Development', 'Industry Experience', 'Teamwork', 'Project Management'],
          milestones: [
            { id: 11, text: 'Secure internship at Andela/Flutterwave', deadline: `${currentYear + 3}-03-01`, completed: false },
            { id: 12, text: 'Contribute to 3 open source projects', deadline: `${currentYear + 3}-12-01`, completed: false },
            { id: 13, text: 'Attend 2 major tech conferences', deadline: `${currentYear + 4}-06-01`, completed: false }
          ],
          resources: [
            'Company career pages',
            'GitHub open source projects',
            'Tech conference listings',
            'Professional mentorship programs'
          ]
        },
        {
          id: 'first-job',
          title: 'First Job',
          subtitle: 'Junior Software Engineer',
          duration: '2-3 years',
          status: 'future',
          progress: 0,
          actions: [
            'Excel in first role',
            'Build strong professional reputation',
            'Develop leadership skills',
            'Plan career advancement'
          ],
          skills: ['Professional Excellence', 'Leadership', 'Mentoring', 'Strategic Thinking'],
          milestones: [
            { id: 14, text: 'Land first job at ₦3M+ annually', deadline: `${currentYear + 5}-01-01`, completed: false },
            { id: 15, text: 'Get promoted to mid-level', deadline: `${currentYear + 6}-06-01`, completed: false },
            { id: 16, text: 'Mentor junior developers', deadline: `${currentYear + 7}-01-01`, completed: false }
          ],
          resources: [
            'Job search platforms',
            'Professional development courses',
            'Industry certifications',
            'Leadership training programs'
          ]
        },
        {
          id: 'career-goal',
          title: '5-Year Career Goal',
          subtitle: 'Senior Software Engineer / Tech Lead',
          duration: 'Long-term',
          status: 'future',
          progress: 0,
          actions: [
            'Achieve senior technical role',
            'Lead development teams',
            'Contribute to technical strategy',
            'Consider entrepreneurship options'
          ],
          skills: ['Technical Leadership', 'Strategic Planning', 'Team Management', 'Innovation'],
          milestones: [
            { id: 17, text: 'Reach ₦8M+ annual salary', deadline: `${currentYear + 8}-01-01`, completed: false },
            { id: 18, text: 'Lead team of 5+ developers', deadline: `${currentYear + 8}-06-01`, completed: false },
            { id: 19, text: 'Launch own tech startup', deadline: `${currentYear + 10}-01-01`, completed: false }
          ],
          resources: [
            'Executive education programs',
            'Startup incubators',
            'Investment networks',
            'Industry leadership forums'
          ]
        }
      ],
      universities: [
        {
          name: 'University of Lagos',
          ranking: '#1 for Computer Science',
          requirements: '300+ JAMB, 5 O\'Level credits',
          tuition: '₦200,000/year',
          duration: '4 years',
          employmentRate: '95%',
          notableAlumni: ['Sim Shagaya (Founder, Konga)', 'Jason Njoku (Founder, iROKOtv)'],
          campusLife: 'Vibrant tech community, regular hackathons, industry partnerships'
        },
        {
          name: 'Obafemi Awolowo University',
          ranking: '#2 for Computer Science',
          requirements: '280+ JAMB, 5 O\'Level credits',
          tuition: '₦150,000/year',
          duration: '4 years',
          employmentRate: '90%',
          notableAlumni: ['Tayo Oviosu (Founder, Paga)', 'Iyinoluwa Aboyeji (Co-founder, Flutterwave)'],
          campusLife: 'Strong academic focus, research opportunities, beautiful campus'
        },
        {
          name: 'University of Ibadan',
          ranking: '#3 for Computer Science',
          requirements: '270+ JAMB, 5 O\'Level credits',
          tuition: '₦180,000/year',
          duration: '4 years',
          employmentRate: '88%',
          notableAlumni: ['Adebayo Ogunlesi (Chairman, GIP)', 'Funke Opeke (CEO, MainOne)'],
          campusLife: 'Historic institution, strong alumni network, research focus'
        }
      ],
      financialPlanning: {
        totalCost: '₦3,500,000',
        breakdown: [
          { item: 'University Tuition (4 years)', cost: '₦800,000' },
          { item: 'Accommodation & Living', cost: '₦1,200,000' },
          { item: 'Books & Materials', cost: '₦300,000' },
          { item: 'Technology & Equipment', cost: '₦500,000' },
          { item: 'Certification & Training', cost: '₦400,000' },
          { item: 'Miscellaneous', cost: '₦300,000' }
        ],
        fundingSources: [
          'Family contribution: 60%',
          'Scholarships: 25%',
          'Part-time work: 10%',
          'Student loans: 5%'
        ]
      }
    };

    setRoadmapData(roadmap);
  };

  useEffect(() => {
    generateRoadmap();
    
    // Load completed milestones from localStorage
    const saved = localStorage.getItem('completedMilestones');
    if (saved) {
      setCompletedMilestones(JSON.parse(saved));
    }
  }, [selectedCareer]);

  const toggleMilestone = (milestoneId) => {
    const newCompleted = completedMilestones.includes(milestoneId)
      ? completedMilestones.filter(id => id !== milestoneId)
      : [...completedMilestones, milestoneId];
    
    setCompletedMilestones(newCompleted);
    localStorage.setItem('completedMilestones', JSON.stringify(newCompleted));
  };

  const getPhaseProgress = (phase) => {
    const totalMilestones = phase.milestones.length;
    const completedCount = phase.milestones.filter(m => completedMilestones.includes(m.id)).length;
    return totalMilestones > 0 ? Math.round((completedCount / totalMilestones) * 100) : 0;
  };

  const getOverallProgress = () => {
    if (!roadmapData) return 0;
    const totalMilestones = roadmapData.phases.reduce((sum, phase) => sum + phase.milestones.length, 0);
    return totalMilestones > 0 ? Math.round((completedMilestones.length / totalMilestones) * 100) : 0;
  };

  const exportRoadmap = () => {
    const content = `
CAREER ROADMAP: ${roadmapData.career}
Generated by YabvilPrep Career Compass

OVERVIEW:
- Total Duration: ${roadmapData.totalDuration}
- Overall Progress: ${getOverallProgress()}%

PHASES:
${roadmapData.phases.map(phase => `
${phase.title} (${phase.duration})
${phase.subtitle}
Progress: ${getPhaseProgress(phase)}%

Actions:
${phase.actions.map(action => `• ${action}`).join('\n')}

Milestones:
${phase.milestones.map(m => `${completedMilestones.includes(m.id) ? '✓' : '○'} ${m.text} (${m.deadline})`).join('\n')}

Skills to Develop:
${phase.skills.map(skill => `• ${skill}`).join('\n')}

Resources:
${phase.resources.map(resource => `• ${resource}`).join('\n')}
`).join('\n')}

FINANCIAL PLANNING:
Total Estimated Cost: ${roadmapData.financialPlanning.totalCost}

Cost Breakdown:
${roadmapData.financialPlanning.breakdown.map(item => `• ${item.item}: ${item.cost}`).join('\n')}

Funding Sources:
${roadmapData.financialPlanning.fundingSources.map(source => `• ${source}`).join('\n')}

Generated on: ${new Date().toLocaleDateString()}
    `;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${roadmapData.career.replace(/\s+/g, '_')}_Roadmap.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!roadmapData) {
    return <div className="p-8 text-center">Loading roadmap...</div>;
  }

  if (showUniversities) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-100 via-blue-100 to-indigo-100 p-4">
        <div className="max-w-6xl mx-auto">
          <div className="bg-white rounded-2xl shadow-xl p-8">
            <div className="flex items-center justify-between mb-6">
              <button
                onClick={() => setShowUniversities(false)}
                className="text-indigo-600 hover:text-indigo-700 font-semibold"
              >
                ← Back to Roadmap
              </button>
              <h1 className="text-2xl font-bold text-gray-800">University Recommendations</h1>
            </div>

            <div className="grid md:grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
              {roadmapData.universities.map((uni, index) => (
                <div key={uni.name} className="border border-gray-200 rounded-xl p-6">
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-xl font-bold text-gray-800">{uni.name}</h3>
                    <span className="bg-indigo-100 text-indigo-800 px-2 py-1 rounded text-sm font-medium">
                      {uni.ranking}
                    </span>
                  </div>

                  <div className="space-y-3 text-sm">
                    <div className="flex justify-between">
                      <span className="text-gray-600">Requirements:</span>
                      <span className="font-medium">{uni.requirements}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Tuition:</span>
                      <span className="font-medium text-green-600">{uni.tuition}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Duration:</span>
                      <span className="font-medium">{uni.duration}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-gray-600">Employment Rate:</span>
                      <span className="font-medium text-blue-600">{uni.employmentRate}</span>
                    </div>
                  </div>

                  <div className="mt-4">
                    <h4 className="font-semibold text-gray-800 mb-2">Notable Alumni</h4>
                    <ul className="text-sm text-gray-600 space-y-1">
                      {uni.notableAlumni.map((alumni, i) => (
                        <li key={i}>• {alumni}</li>
                      ))}
                    </ul>
                  </div>

                  <div className="mt-4">
                    <h4 className="font-semibold text-gray-800 mb-2">Campus Life</h4>
                    <p className="text-sm text-gray-600">{uni.campusLife}</p>
                  </div>

                  <button className="w-full mt-4 bg-indigo-600 hover:bg-indigo-700 text-white py-2 px-4 rounded-lg font-semibold transition">
                    Learn More
                  </button>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-100 via-blue-100 to-indigo-100 p-4">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="bg-white rounded-2xl shadow-xl p-8 mb-6">
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-4">
              <div className="w-16 h-16 bg-gradient-to-r from-green-600 to-teal-600 rounded-full flex items-center justify-center">
                <MapPin className="w-8 h-8 text-white" />
              </div>
              <div>
                <h1 className="text-3xl font-bold text-gray-800">Career Roadmap</h1>
                <p className="text-gray-600">Your personalized path to {roadmapData.career}</p>
              </div>
            </div>
            <div className="text-right">
              <div className="text-3xl font-bold text-green-600">{getOverallProgress()}%</div>
              <div className="text-gray-600">Complete</div>
            </div>
          </div>

          <div className="grid md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="text-2xl font-bold text-blue-600">{roadmapData.totalDuration}</div>
              <div className="text-gray-600">Total Journey</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-indigo-600">{completedMilestones.length}</div>
              <div className="text-gray-600">Milestones Completed</div>
            </div>
            <div className="text-center">
              <div className="text-2xl font-bold text-orange-600">
                {roadmapData.phases.filter(p => getPhaseProgress(p) > 0).length}
              </div>
              <div className="text-gray-600">Phases Started</div>
            </div>
          </div>

          <div className="flex justify-center gap-4 mt-6">
            <button
              onClick={() => setShowUniversities(true)}
              className="px-6 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-semibold transition flex items-center gap-2"
            >
              <BookOpen className="w-5 h-5" />
              View Universities
            </button>
            <button
              onClick={exportRoadmap}
              className="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg font-semibold hover:bg-gray-50 transition flex items-center gap-2"
            >
              <Download className="w-5 h-5" />
              Export Roadmap
            </button>
          </div>
        </div>

        {/* Timeline */}
        <div className="bg-white rounded-2xl shadow-xl p-8">
          <h2 className="text-2xl font-bold text-gray-800 mb-8">Your Journey Timeline</h2>
          
          <div className="relative">
            {/* Timeline line */}
            <div className="absolute left-8 top-0 bottom-0 w-1 bg-gradient-to-b from-green-500 via-blue-500 to-indigo-500"></div>
            
            <div className="space-y-8">
              {roadmapData.phases.map((phase, index) => (
                <div key={phase.id} className="relative flex items-start gap-6">
                  {/* Timeline node */}
                  <div className={`w-16 h-16 rounded-full flex items-center justify-center text-white font-bold text-lg z-10 ${
                    phase.status === 'active' ? 'bg-green-500' :
                    phase.status === 'upcoming' ? 'bg-blue-500' :
                    'bg-gray-400'
                  }`}>
                    {phase.status === 'active' ? <Target className="w-8 h-8" /> :
                     getPhaseProgress(phase) > 0 ? <CheckCircle className="w-8 h-8" /> :
                     <Clock className="w-8 h-8" />}
                  </div>

                  {/* Phase content */}
                  <div className="flex-1 bg-gray-50 rounded-xl p-6">
                    <div className="flex items-center justify-between mb-4">
                      <div>
                        <h3 className="text-xl font-bold text-gray-800">{phase.title}</h3>
                        <p className="text-gray-600">{phase.subtitle} • {phase.duration}</p>
                      </div>
                      <div className="text-right">
                        <div className="text-2xl font-bold text-indigo-600">{getPhaseProgress(phase)}%</div>
                        <div className="text-sm text-gray-500">Progress</div>
                      </div>
                    </div>

                    <div className="grid md:grid-cols-2 gap-6">
                      <div>
                        <h4 className="font-semibold text-gray-800 mb-3">Key Actions</h4>
                        <ul className="space-y-2 text-sm">
                          {phase.actions.map((action, i) => (
                            <li key={i} className="flex items-start gap-2">
                              <div className="w-2 h-2 bg-indigo-500 rounded-full mt-2 flex-shrink-0"></div>
                              <span>{action}</span>
                            </li>
                          ))}
                        </ul>
                      </div>

                      <div>
                        <h4 className="font-semibold text-gray-800 mb-3">Milestones</h4>
                        <div className="space-y-2">
                          {phase.milestones.map((milestone) => (
                            <div key={milestone.id} className="flex items-center gap-3">
                              <button
                                onClick={() => toggleMilestone(milestone.id)}
                                className={`w-5 h-5 rounded border-2 flex items-center justify-center transition ${
                                  completedMilestones.includes(milestone.id)
                                    ? 'bg-green-500 border-green-500 text-white'
                                    : 'border-gray-300 hover:border-green-500'
                                }`}
                              >
                                {completedMilestones.includes(milestone.id) && (
                                  <CheckCircle className="w-3 h-3" />
                                )}
                              </button>
                              <div className="flex-1">
                                <div className={`text-sm ${
                                  completedMilestones.includes(milestone.id) 
                                    ? 'line-through text-gray-500' 
                                    : 'text-gray-700'
                                }`}>
                                  {milestone.text}
                                </div>
                                <div className="text-xs text-gray-500">{milestone.deadline}</div>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>

                    <div className="mt-4 pt-4 border-t border-gray-200">
                      <div className="flex flex-wrap gap-2 mb-3">
                        <span className="text-sm font-medium text-gray-700">Skills to develop:</span>
                        {phase.skills.map((skill, i) => (
                          <span key={i} className="bg-blue-100 text-blue-800 px-2 py-1 rounded text-xs">
                            {skill}
                          </span>
                        ))}
                      </div>
                      
                      <button
                        onClick={() => setSelectedPhase(selectedPhase === phase.id ? null : phase.id)}
                        className="text-indigo-600 hover:text-indigo-700 text-sm font-medium"
                      >
                        {selectedPhase === phase.id ? 'Hide Resources' : 'Show Resources & Details'}
                      </button>

                      {selectedPhase === phase.id && (
                        <div className="mt-4 bg-white rounded-lg p-4">
                          <h5 className="font-semibold text-gray-800 mb-2">Recommended Resources</h5>
                          <ul className="text-sm text-gray-600 space-y-1">
                            {phase.resources.map((resource, i) => (
                              <li key={i}>• {resource}</li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Financial Planning */}
        <div className="bg-white rounded-2xl shadow-xl p-8 mt-6">
          <h2 className="text-2xl font-bold text-gray-800 mb-6 flex items-center gap-2">
            <DollarSign className="w-6 h-6 text-green-600" />
            Financial Planning
          </h2>
          
          <div className="grid md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-lg font-semibold text-gray-800 mb-4">
                Total Estimated Cost: {roadmapData.financialPlanning.totalCost}
              </h3>
              <div className="space-y-3">
                {roadmapData.financialPlanning.breakdown.map((item, index) => (
                  <div key={index} className="flex justify-between items-center p-3 bg-gray-50 rounded-lg">
                    <span className="text-gray-700">{item.item}</span>
                    <span className="font-semibold text-gray-800">{item.cost}</span>
                  </div>
                ))}
              </div>
            </div>

            <div>
              <h3 className="text-lg font-semibold text-gray-800 mb-4">Funding Strategy</h3>
              <div className="space-y-2">
                {roadmapData.financialPlanning.fundingSources.map((source, index) => (
                  <div key={index} className="flex items-center gap-3 p-3 bg-green-50 rounded-lg">
                    <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                    <span className="text-green-800">{source}</span>
                  </div>
                ))}
              </div>
              
              <div className="mt-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                <h4 className="font-semibold text-yellow-800 mb-2">💡 Money-Saving Tips</h4>
                <ul className="text-sm text-yellow-700 space-y-1">
                  <li>• Apply for merit-based scholarships early</li>
                  <li>• Consider federal universities for lower tuition</li>
                  <li>• Look into tech company sponsorship programs</li>
                  <li>• Start freelancing during university for income</li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CareerRoadmapGenerator;